variable "oci_tenancy" {} 
variable "oci_user" {}
variable "oci_fingerprint" {}
variable "oci_key" {}
variable "oci_region" {}
variable "oci_compartment" {}
variable "private_key_file" {}
variable "public_key" {}
#variable "home_region" {}
